python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 1
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 2
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 3
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 4
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 5
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 6
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 7
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 8
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 9
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 10
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 11
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 12
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 13
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 14
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 15
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 16
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 17
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 18
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 19
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 20
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 21
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 22
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 23
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 24
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 25
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 26
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 27
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 28
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 29
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 30
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 31
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 32
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 33
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 34
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 35
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 36
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 37
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 38
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 39
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 40
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 41
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 42
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 43
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 44
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 45
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 46
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 47
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 48
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 49
python score_DirMult_2d_simu.py -n 10 -s eqocc -t -r 50
