python score_DirMult.py -n 10 -s eqocc  -r 31
python score_DirMult.py -n 10 -s eqocc  -r 32
python score_DirMult.py -n 10 -s eqocc  -r 33
python score_DirMult.py -n 10 -s eqocc  -r 34
python score_DirMult.py -n 10 -s eqocc  -r 35
python score_DirMult.py -n 10 -s eqocc  -r 36
python score_DirMult.py -n 10 -s eqocc  -r 37
python score_DirMult.py -n 10 -s eqocc  -r 38
python score_DirMult.py -n 10 -s eqocc  -r 39
python score_DirMult.py -n 10 -s eqocc  -r 40
python score_DirMult.py -n 10 -s eqocc  -r 41
python score_DirMult.py -n 10 -s eqocc  -r 42
python score_DirMult.py -n 10 -s eqocc  -r 43
python score_DirMult.py -n 10 -s eqocc  -r 44
python score_DirMult.py -n 10 -s eqocc  -r 45
python score_DirMult.py -n 10 -s eqocc  -r 46
python score_DirMult.py -n 10 -s eqocc  -r 47
python score_DirMult.py -n 10 -s eqocc  -r 48
python score_DirMult.py -n 10 -s eqocc  -r 49
python score_DirMult.py -n 10 -s eqocc  -r 50
