python score_DirMult_2d_simu.py -n 10 -s eqocc -r 1
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 2
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 3
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 4
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 5
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 6
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 7
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 8
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 9
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 10
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 11
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 12
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 13
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 14
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 15
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 16
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 17
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 18
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 19
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 20
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 21
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 22
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 23
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 24
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 25
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 26
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 27
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 28
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 29
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 30
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 31
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 32
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 33
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 34
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 35
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 36
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 37
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 38
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 39
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 40
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 41
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 42
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 43
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 44
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 45
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 46
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 47
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 48
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 49
python score_DirMult_2d_simu.py -n 10 -s eqocc -r 50
