python score_DirMult_2d_simu.py -n 10 -s width -r 1
python score_DirMult_2d_simu.py -n 10 -s width -r 2
python score_DirMult_2d_simu.py -n 10 -s width -r 3
python score_DirMult_2d_simu.py -n 10 -s width -r 4
python score_DirMult_2d_simu.py -n 10 -s width -r 5
python score_DirMult_2d_simu.py -n 10 -s width -r 6
python score_DirMult_2d_simu.py -n 10 -s width -r 7
python score_DirMult_2d_simu.py -n 10 -s width -r 8
python score_DirMult_2d_simu.py -n 10 -s width -r 9
python score_DirMult_2d_simu.py -n 10 -s width -r 10
python score_DirMult_2d_simu.py -n 10 -s width -r 11
python score_DirMult_2d_simu.py -n 10 -s width -r 12
python score_DirMult_2d_simu.py -n 10 -s width -r 13
python score_DirMult_2d_simu.py -n 10 -s width -r 14
python score_DirMult_2d_simu.py -n 10 -s width -r 15
python score_DirMult_2d_simu.py -n 10 -s width -r 16
python score_DirMult_2d_simu.py -n 10 -s width -r 17
python score_DirMult_2d_simu.py -n 10 -s width -r 18
python score_DirMult_2d_simu.py -n 10 -s width -r 19
python score_DirMult_2d_simu.py -n 10 -s width -r 20
python score_DirMult_2d_simu.py -n 10 -s width -r 21
python score_DirMult_2d_simu.py -n 10 -s width -r 22
python score_DirMult_2d_simu.py -n 10 -s width -r 23
python score_DirMult_2d_simu.py -n 10 -s width -r 24
python score_DirMult_2d_simu.py -n 10 -s width -r 25
python score_DirMult_2d_simu.py -n 10 -s width -r 26
python score_DirMult_2d_simu.py -n 10 -s width -r 27
python score_DirMult_2d_simu.py -n 10 -s width -r 28
python score_DirMult_2d_simu.py -n 10 -s width -r 29
python score_DirMult_2d_simu.py -n 10 -s width -r 30
python score_DirMult_2d_simu.py -n 10 -s width -r 31
python score_DirMult_2d_simu.py -n 10 -s width -r 32
python score_DirMult_2d_simu.py -n 10 -s width -r 33
python score_DirMult_2d_simu.py -n 10 -s width -r 34
python score_DirMult_2d_simu.py -n 10 -s width -r 35
python score_DirMult_2d_simu.py -n 10 -s width -r 36
python score_DirMult_2d_simu.py -n 10 -s width -r 37
python score_DirMult_2d_simu.py -n 10 -s width -r 38
python score_DirMult_2d_simu.py -n 10 -s width -r 39
python score_DirMult_2d_simu.py -n 10 -s width -r 40
python score_DirMult_2d_simu.py -n 10 -s width -r 41
python score_DirMult_2d_simu.py -n 10 -s width -r 42
python score_DirMult_2d_simu.py -n 10 -s width -r 43
python score_DirMult_2d_simu.py -n 10 -s width -r 44
python score_DirMult_2d_simu.py -n 10 -s width -r 45
python score_DirMult_2d_simu.py -n 10 -s width -r 46
python score_DirMult_2d_simu.py -n 10 -s width -r 47
python score_DirMult_2d_simu.py -n 10 -s width -r 48
python score_DirMult_2d_simu.py -n 10 -s width -r 49
python score_DirMult_2d_simu.py -n 10 -s width -r 50
