python score_DirMult.py -n 10 -s width -t -r 31
python score_DirMult.py -n 10 -s width -t -r 32
python score_DirMult.py -n 10 -s width -t -r 33
python score_DirMult.py -n 10 -s width -t -r 34
python score_DirMult.py -n 10 -s width -t -r 35
python score_DirMult.py -n 10 -s width -t -r 36
python score_DirMult.py -n 10 -s width -t -r 37
python score_DirMult.py -n 10 -s width -t -r 38
python score_DirMult.py -n 10 -s width -t -r 39
python score_DirMult.py -n 10 -s width -t -r 40
python score_DirMult.py -n 10 -s width -t -r 41
python score_DirMult.py -n 10 -s width -t -r 42
python score_DirMult.py -n 10 -s width -t -r 43
python score_DirMult.py -n 10 -s width -t -r 44
python score_DirMult.py -n 10 -s width -t -r 45
python score_DirMult.py -n 10 -s width -t -r 46
python score_DirMult.py -n 10 -s width -t -r 47
python score_DirMult.py -n 10 -s width -t -r 48
python score_DirMult.py -n 10 -s width -t -r 49
python score_DirMult.py -n 10 -s width -t -r 50
